"use client"
import { styled } from 'styled-components'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LinesContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: -1;

  display: flex;
  justify-content: space-around;

  div{
    width: 1px;
    height: 100vh; 
    background-color: var(--color-border);
    color: var(--color-border);

    display: flex;
    flex-direction: column;
    justify-content: space-around;
    align-items: center;
    font-size: 15px;
    font-weight: bolder;

  }
`

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LinesContainer>
          <div>
            <p>o</p>
            <p>x</p>
            <p>o</p>
          </div>
          
          <div>
            <p>o</p>
            <p>x</p>
            <p>o</p>
          </div>
          <div>
            <p>o</p>
            <p>x</p>
            <p>o</p>
          </div>
          <div>
            <p>o</p>
            <p>x</p>
            <p>o</p>
          </div>
        </LinesContainer>
        {children}
      </body>
    </html>
  )
}
